
package visao;

import controle.OperacaoDoacao;
import controle.OperacaoGastos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Gasto;


public class Listar_Gasto extends javax.swing.JFrame {
    private boolean per;
   
    OperacaoGastos opGastos;
    
    public Listar_Gasto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btn_modulo = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtData2 = new javax.swing.JFormattedTextField();
        txtData1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        Tabela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Gasto = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_atualiza2 = new javax.swing.JButton();
        btn_excluir2 = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalDoacoes = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalGastos = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalTUDO = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 18, 30));

        btn_modulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/bt_modulo1.jpg"))); // NOI18N
        btn_modulo.setToolTipText("MODULOS");
        btn_modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moduloActionPerformed(evt);
            }
        });

        btRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/seta.png"))); // NOI18N
        btRetornar.setToolTipText("VOLTAR");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/APAE.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/logo_sistema.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/logo_gastos.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 18, 30));

        jLabel1.setForeground(new java.awt.Color(62, 150, 206));
        jLabel1.setText("De:");

        try {
            txtData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setForeground(new java.awt.Color(62, 150, 206));
        jLabel2.setText("Até:");

        Tabela.setBackground(new java.awt.Color(0, 18, 30));
        Tabela.setForeground(new java.awt.Color(62, 150, 206));
        Tabela.setText("Ok");
        Tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabelaActionPerformed(evt);
            }
        });

        tabela_Gasto.setBackground(new java.awt.Color(0, 18, 30));
        tabela_Gasto.setForeground(new java.awt.Color(62, 150, 206));
        tabela_Gasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Gasto.setToolTipText("");
        tabela_Gasto.setSelectionForeground(new java.awt.Color(62, 150, 206));
        jScrollPane1.setViewportView(tabela_Gasto);

        jLabel8.setForeground(new java.awt.Color(62, 150, 206));
        jLabel8.setText("Descrição:");

        jLabel9.setForeground(new java.awt.Color(62, 150, 206));
        jLabel9.setText("Valor:");

        jLabel10.setForeground(new java.awt.Color(62, 150, 206));
        jLabel10.setText("Data:");

        btn_atualiza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/ATUALIZAR.png"))); // NOI18N
        btn_atualiza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualiza2ActionPerformed(evt);
            }
        });

        btn_excluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/EXCLUIR.png"))); // NOI18N
        btn_excluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir2ActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btn_atualiza2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_atualiza2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 18, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor total de doações:");

        txtTotalDoacoes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalDoacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDoacoesActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor total de Gastos:");

        txtTotalGastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtTotalGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalGastosActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TOTAL (GASTOS-DOAÇÕES)");

        txtTotalTUDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalTUDOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotalTUDO)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalDoacoes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalGastos, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDoacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalTUDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(376, 376, 376)))
                        .addComponent(btn_modulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel5)))
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRetornar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_modulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(90, 90, 90)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moduloActionPerformed
        Tela_Modulos tM = new Tela_Modulos();
        tM.permissao(per);
        tM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_moduloActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
        Operacao_Gasto oD = new Operacao_Gasto();
        oD.permissao(per);
        oD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRetornarActionPerformed

    private void TabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabelaActionPerformed
        Gasto gasto = null;
        carregarTabela(gasto);
    }//GEN-LAST:event_TabelaActionPerformed

    private void btn_atualiza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualiza2ActionPerformed
        Date s=null;
       
        if((tabela_Gasto.getSelectedRow() == -1) && (txtData.getText()!="")&&(txtValor.getText()!="")&&(txtDescricao.getText()!="")){
                JOptionPane.showMessageDialog(null, "Selecione uma linha para alterar e complete os campos" );
        }else{
            try{
                int linhaSelecionada = tabela_Gasto.getSelectedRow(); 
             
                int id = Integer.parseInt(tabela_Gasto.getValueAt(linhaSelecionada, 0).toString());
                String desc = tabela_Gasto.getValueAt(linhaSelecionada, 1).toString();
                Float valort = Float.parseFloat(tabela_Gasto.getValueAt(linhaSelecionada, 2).toString());
                String datat = tabela_Gasto.getValueAt(linhaSelecionada, 3).toString();
                String tipo=txtDescricao.getText();
                s=conv(datat);
                Date prazoII = conv(txtData.getText());
                java.sql.Date datan;
                datan = new java.sql.Date(s.getTime());
                java.sql.Date data1;
                data1 = new java.sql.Date(prazoII.getTime());
                long cpf = 0;
                Gasto dados = null;
                dados = new Gasto(
                    tipo,
                    Float.parseFloat(txtValor.getText()),
                    data1,
                    id
                );
                System.out.println("Indo pra doação");
                opGastos = new OperacaoGastos();
                opGastos.atualizaT(dados,id);
                carregarTabela(dados);
                limpaCampo();
                
                atualizarGastosTotal();
                JOptionPane.showMessageDialog(null, "Atualização Efetuada!");
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Formato inválido!");
            }
            
        }
    }//GEN-LAST:event_btn_atualiza2ActionPerformed

    private void btn_excluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir2ActionPerformed
        Date s = null;
        Gasto gasto = new Gasto();
        opGastos = new OperacaoGastos();
        
        String idt = tabela_Gasto.getValueAt(tabela_Gasto.getSelectedRow(), 0).toString();

        
        try {
            gasto.setId(Integer.parseInt(idt));
 
               
            opGastos.cancelar(gasto);
            
            carregarTabela(gasto);
            
            atualizarGastosTotal();
            JOptionPane.showMessageDialog(null, "Gasto removido com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato inválido!");
        }
    }//GEN-LAST:event_btn_excluir2ActionPerformed

    private void txtTotalDoacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDoacoesActionPerformed
        OperacaoDoacao dd = new OperacaoDoacao();
        float r = dd.somaDoacoes();
        String s = Float.toString(r);
        txtTotalDoacoes.setText(s);
    }//GEN-LAST:event_txtTotalDoacoesActionPerformed

    private void txtTotalGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalGastosActionPerformed
        OperacaoGastos dd = new OperacaoGastos();
        float r = dd.somaGastos();
        String s = Float.toString(r);
        txtTotalGastos.setText(s);
    }//GEN-LAST:event_txtTotalGastosActionPerformed

    private void txtTotalTUDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalTUDOActionPerformed
        OperacaoDoacao dd = new OperacaoDoacao();
        OperacaoGastos dd1 = new OperacaoGastos();
        float r = dd.somaDoacoes() - dd1.somaGastos();
        String s = Float.toString(r);
        txtTotalTUDO.setText(s);
    }//GEN-LAST:event_txtTotalTUDOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_Gasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tabela;
    private javax.swing.JButton btRetornar;
    private javax.swing.JButton btn_atualiza2;
    private javax.swing.JButton btn_excluir2;
    private javax.swing.JButton btn_modulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabela_Gasto;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtData1;
    private javax.swing.JFormattedTextField txtData2;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtTotalDoacoes;
    private javax.swing.JFormattedTextField txtTotalGastos;
    private javax.swing.JFormattedTextField txtTotalTUDO;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    
    private Date conv(String data) {
        SimpleDateFormat exib=new SimpleDateFormat("dd/MM/yyyy");
        Date nova=null;
        try {
            nova =exib.parse(data);           
        } catch (ParseException ex) {
            Logger.getLogger(null,"Data inválida");
        }
 
        return nova;
    }
    private String convIn(String data) {
        SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat form2 = new SimpleDateFormat("dd/MM/yyyy");
        Date s=null;
        try {
                    s=form.parse(data);
        } catch (ParseException ex) {
                    Logger.getLogger(Lista_DoacoesE.class.getName()).log(Level.SEVERE, null, ex);
        }
        String retorno=form2.format(s);
        return retorno;
    }

    void permissao(boolean x) {
        per = x;
    }

    private void carregarTabela(Gasto gasto) {
        DefaultTableModel gastoModel = (DefaultTableModel) tabela_Gasto.getModel();
        for (int i = gastoModel.getRowCount()-1; i >= 0; i--) {
            gastoModel.removeRow(i);
        }
        
        Date d1=null;
        d1=conv(txtData2.getText());
        Date d2=null;
        d2=conv(txtData1.getText());
               java.sql.Date datan1;
               datan1 = new java.sql.Date(d1.getTime());
               java.sql.Date datan2;
               datan2 = new java.sql.Date(d2.getTime());
        OperacaoGastos opGasto = new OperacaoGastos(); 
        
        for (Gasto gastos : opGasto.visualizaLista(null,datan1,datan2)) {
            String[] myList = {
                new String(String.valueOf(gastos.getId())),
                new String(String.valueOf(gastos.getTipo())),
                new String(String.valueOf(gastos.getValor())),
                new String(String.valueOf(convIn(String.valueOf(gastos.getData())))),};
            gastoModel.addRow(myList);
        }
        
    }
    public void setValores(float v,float vd,float vt){
        String valorg=String.valueOf(v);
        String valord=String.valueOf(vd);
        String valort=String.valueOf(vt);
        txtTotalGastos.setText(valorg);
        txtTotalDoacoes.setText(valord);
        txtTotalTUDO.setText(valort);
        
    }

    private void limpaCampo() {
        txtDescricao.setText("");
        txtValor.setText("");
        txtData.setText("");
    }
    
    private void atualizarGastosTotal(){
        OperacaoDoacao dd = new OperacaoDoacao();
        OperacaoGastos dd1 = new OperacaoGastos();
        
        float rd = dd.somaDoacoes();
        String sd = Float.toString(rd);
        txtTotalDoacoes.setText(sd);
        
        float rg = dd1.somaGastos();
        String sg = Float.toString(rg);
        txtTotalGastos.setText(sg);
        
        float rs = dd.somaDoacoes() - dd1.somaGastos();
        String ss = Float.toString(rs);
        txtTotalTUDO.setText(ss);
    }
}
